### ISSUE TITLE
Add blue color for Eitr food

### ISSUE THREAD

**Issue by nbusseneau** [jneb802/Food_Slot_Colors#1]
Hey, love your mods, thanks a lot :)

I would love to see support for Eitr food with a blue-colored background. What do you think?

**Comment by nbusseneau** [comment]
Sent a pull request for this at #2 :)

**Comment by jneb802** [comment]
Hey friend! Yea that's a great idea!! Thanks so much for submitting the PR. I will review and test in the next few days!

**Comment by nbusseneau** [comment]
As discussed offline, superseded by https://github.com/nbusseneau/ColoredFoodUI.
